services:
    pecserke_ics_dhcp_server_management.ssh.key_store.chain:
        class: Pecserke\Component\FileLoader\Ssh\ChainKeyStore

    pecserke_ics_dhcp_server_management.ssh.key_store.json:
        class: Pecserke\Component\FileLoader\Ssh\JsonKeyStore
        arguments: [ "%pecserke_ics_dhcp_server_management.ssh.key_store.json.file%" ]
        tags:
            -  { name: pecserke_ics_dhcp_server_management.ssh_key_store }

    pecserke_ics_dhcp_server_management.ssh.key_store:
        alias: pecserke_ics_dhcp_server_management.ssh.key_store.chain

    pecserke_ics_dhcp_server_management.loader.scp:
        class: Pecserke\Component\FileLoader\ScpLoader
        arguments:
            - "@pecserke_ics_dhcp_server_management.ssh.key_store"

    pecserke_ics_dhcp_server_management.loader.file:
        class: Pecserke\Component\FileLoader\FileLoader

    pecserke_ics_dhcp_server_management.loader.chain:
        class: Pecserke\Component\FileLoader\ChainLoader
        calls:
            - [ registerLoader, [ "@pecserke_ics_dhcp_server_management.loader.file" ] ]
            - [ registerLoader, [ "@pecserke_ics_dhcp_server_management.loader.scp" ] ]

    pecserke_ics_dhcp_server_management.loader:
        alias: pecserke_ics_dhcp_server_management.loader.chain

    pecserke_ics_dhcp_server_management.parser.lease:
        class: Pecserke\Component\IcsDhcpServer\Parser\LeaseParser

    pecserke_ics_dhcp_server_management.parser.host:
        class: Pecserke\Component\IcsDhcpServer\Parser\HostParser

    pecserke_ics_dhcp_server_management.repository.lease:
        class: Pecserke\Bundle\IcsDhcpServerManagementBundle\Repository\LeaseRepository
        arguments:
            - "@pecserke_ics_dhcp_server_management.parser.lease"
            - "@pecserke_ics_dhcp_server_management.loader"
            - "%pecserke_ics_dhcp_server_management.repository.lease.uri%"

    pecserke_ics_dhcp_server_management.repository.host:
        class: Pecserke\Bundle\IcsDhcpServerManagementBundle\Repository\HostRepository
        arguments:
            - "@pecserke_ics_dhcp_server_management.parser.host"
            - "@pecserke_ics_dhcp_server_management.loader"
            - "%pecserke_ics_dhcp_server_management.repository.hosts.uri%"

    pecserke_ics_dhcp_server_management.command.lease.list:
        class: Pecserke\Bundle\IcsDhcpServerManagementBundle\Command\Lease\ListCommand
        arguments: [ "@pecserke_ics_dhcp_server_management.repository.lease" ]
        tags:
            -  { name: console.command }

    pecserke_ics_dhcp_server_management.command.host.list:
        class: Pecserke\Bundle\IcsDhcpServerManagementBundle\Command\Host\ListCommand
        arguments: [ "@pecserke_ics_dhcp_server_management.repository.host" ]
        tags:
            -  { name: console.command }
